FROM n8nio/n8n:latest

# install python
USER root
RUN apk update && \
    apk add --update python3 py3-pip && \
    apk add build-base 

USER node
RUN python3 -m pip install --user --break-system-packages pipx

ENV PATH="/home/node/.local/bin:$PATH"
